---
# Install fluentd (td-agent) on all servers
- hosts: all
  remote_user: root
  vars:
    # If you don't want to download the RPM file, comment out `td_agent_url`.
    # You will then need to provide the RPM file inside the config directory.
    td_agent_url: https://packages.treasuredata.com/2/redhat/7/x86_64
    td_agent_rpm: td-agent-2.2.0-0.x86_64.rpm
    td_agent_uid: 123456

    # Plugins for fluentd
    fluent_plugins:
      - name: fluent-plugin-concat
        version: 1.0.0
      - name: fluent-plugin-kubernetes
        version: 0.3.1

    # Proxy settings if required
    proxy_env:
      http_proxy: ""
      https_proxy: ""

  tasks:
  # Download RPM file from the Internet
  - name: Download tg-agent RPM file
    get_url:
      url: "{{ td_agent_url }}/{{ td_agent_rpm }}"
      dest: /tmp/{{ td_agent_rpm }}
    environment: "{{ proxy_env }}"
    when: td_agent_url is defined

  # Copy RPM file instead of downloading it
  - name: Copy tg-agent RPM file
    copy:
      src: "{{ td_agent_rpm }}"
      dest: /tmp/{{ td_agent_rpm }}
    when: td_agent_url is not defined

  - name: Install td-agent
    yum:
      name: /tmp/{{ td_agent_rpm }}
      state: present
    notify:
      - restart td-agent

  - name: Create td-agent group
    group:
      name: td-agent
      gid: "{{ td_agent_uid }}"

  - name: Create td-agent user
    user:
      name: td-agent
      shell: /bin/nologin
      home: /bin/false
      uid: "{{ td_agent_uid }}"
      group: td-agent

  - name: Install plugin dependancies
    yum:
      name: "{{ item }}"
      state: present
    with_items:
      - gcc

  # NOTE: Operators on version (e.g, ">", "<", "!=") currently not supported by gem module
  # - name: Uninstall other versions of fluentd plugins
  #   gem:
  #     name: "{{ item.name }}"
  #     version: "!={{ item.version }}"
  #     state: absent
  #     executable: /opt/td-agent/embedded/bin/gem
  #   with_items: "{{ fluent_plugins }}"
  #   notify:
  #     - restart td-agent

  - name: Uninstall other versions of fluentd plugins
    command: >
      /opt/td-agent/embedded/bin/gem uninstall {{ item.name }}
      --version '!={{ item.version }}' --all
    with_items: "{{ fluent_plugins }}"
    register: command_result
    failed_when:
      - "'is not installed' not in command_result.stderr"
      - command_result.rc != 0
    changed_when:
      - "'Successfully uninstalled' in command_result.stdout"
    notify:
      - restart td-agent

  - name: Install fluentd plugins
    gem:
      name: "{{ item.name }}"
      version: "{{ item.version }}"
      state: present
      user_install: no
      executable: /opt/td-agent/embedded/bin/gem
    environment: "{{ proxy_env }}"
    with_items: "{{ fluent_plugins }}"
    notify:
      - restart td-agent

  - name: Create td-agent config directory
    file:
      path: /etc/td-agent/config.d
      state: directory
      owner: td-agent
      group: td-agent

  - name: Create log directory for td-agent
    file:
      path: /var/log/td-agent/tmp
      state: directory
      owner: td-agent
      group: td-agent

  - name: Create sysconfig file for td-agent
    copy:
      src: "{{ playbook_dir }}/config/sysconfig_tg-agent"
      dest: /etc/sysconfig/td-agent
    notify:
      - restart td-agent

  - name: Include config.d files
    lineinfile:
      dest: /etc/td-agent/td-agent.conf
      insertbefore: BOF
      state: present
      line: "@include config.d/*.conf"
    notify:
      - restart td-agent

  - name: Add fluentd config files
    copy:
      src: "{{ item.src }}"
      dest: /etc/td-agent/config.d/{{ item.dest }}
    with_items:
      - src: "{{ playbook_dir }}/config/td-agent_kubernetes.conf"
        dest: kubernetes.conf
      - src: "{{ playbook_dir }}/config/td-agent_django.conf"
        dest: django.conf
    notify:
      - restart td-agent

  - name: Enable td-agent
    service:
      name: td-agent
      state: started
      enabled: yes

  handlers:
    - name: restart td-agent
      service:
        name: td-agent
        state: restarted
