---
# Download RPM file from the Internet
- name: Download td-agent RPM file
  get_url:
    url: "{{ td_agent_url }}/{{ td_agent_rpm }}"
    dest: "{{ td_agent_rpm_path }}/{{ td_agent_rpm }}"
  environment: "{{ proxy_env }}"
  when: download_td_agent_rpm

# Copy RPM file instead of downloading it
- name: Copy td-agent RPM file
  copy:
    src: "{{ td_agent_rpm }}"
    dest: "{{ td_agent_rpm_path }}/{{ td_agent_rpm }}"
  when: not download_td_agent_rpm

- name: Install td-agent
  yum:
    name: /tmp/{{ td_agent_rpm }}
    state: present
  notify:
    - restart td-agent

- name: Create td-agent group
  group:
    name: td-agent
    gid: "{{ td_agent_uid }}"

- name: Create td-agent user
  user:
    name: td-agent
    shell: /bin/nologin
    home: /bin/false
    uid: "{{ td_agent_uid }}"
    group: td-agent

- name: Install plugin dependancies
  yum:
    name: "{{ item }}"
    state: present
  with_items: "{{ plugin_dependancies }}"

# NOTE: Operators on version (e.g, ">", "<", "!=") currently not supported by gem module
# - name: Uninstall other versions of fluentd plugins
#   gem:
#     name: "{{ item.name }}"
#     version: "!={{ item.version }}"
#     state: absent
#     executable: /opt/td-agent/embedded/bin/gem
#   with_items: "{{ fluent_plugins }}"
#   notify:
#     - restart td-agent

- name: Uninstall other versions of fluentd plugins
  command: >
    /opt/td-agent/embedded/bin/gem uninstall {{ item.name }}
    --version '!={{ item.version }}' --all
  with_items: "{{ fluent_plugins }}"
  register: command_result
  failed_when:
    - "'is not installed' not in command_result.stderr"
    - command_result.rc != 0
  changed_when:
    - "'Successfully uninstalled' in command_result.stdout"
  notify:
    - restart td-agent

- name: Install fluentd plugins
  gem:
    name: "{{ item.name }}"
    version: "{{ item.version }}"
    state: present
    user_install: no
    executable: /opt/td-agent/embedded/bin/gem
  environment: "{{ proxy_env }}"
  with_items: "{{ fluent_plugins }}"
  notify:
    - restart td-agent

- name: Enable td-agent
  service:
    name: td-agent
    state: started
    enabled: yes
