# If you don't want to download the RPM file, comment out `td_agent_url`.
# You will then need to provide the RPM file inside the config directory.
td_agent_url: https://packages.treasuredata.com/2/redhat/7/x86_64
td_agent_rpm: td-agent-2.2.0-0.x86_64.rpm
td_agent_uid: 123456

# Plugins for fluentd
fluent_plugins:
  - name: fluent-plugin-concat
    version: 1.0.0
  - name: fluent-plugin-kubernetes
    version: 0.3.1

plugin_dependancies:
  # Required by fluent-plugin-concat
  - gcc

# Proxy settings if required
proxy_env:
  http_proxy: ""
  https_proxy: ""
