---
# defaults file for fedora_laptop

####################
# Fedora variables #
####################
fedora_installed_packages:
- asciinema
- atomic
- bash-completion
- bcc-tools
- buildah
- ddrescue
- dnf-plugin-system-upgrade
- gnome-tweak-tool
- htop
- ImageMagick
- irssi
- jq
- kompose
- libgnome
- libvirt
- masscan
- nextcloud-client
- nmap
- no-more-secrets
- opensc
- openscap-containers
- openscap-utils
- origin-clients
- podman
- python-ipython
- python-pudb
- python2-heatclient
- python2-openstackclient
- python2-shade
- remmina
- rubygem-asciidoctor-pdf
- scap-security-guide
- screen
- skopeo
- tigervnc
- tmux
- unzip
- vim
- vim-X11
- virt-manager
- VirtualBox
- xsel

fedora_third_party_rpms:
- https://github.com/RocketChat/Rocket.Chat.Electron/releases/download/2.9.0/rocketchat-2.9.0.x86_64.rpm
- https://downloads.slack-edge.com/linux_releases/slack-2.8.0-0.1.fc21.x86_64.rpm

##################
# Atom variables #
##################
atom_installed_packages:
- activate-power-mode
- asciidoc-preview
- autocomplete-ansible
- autocomplete-asciidoc
- autocomplete-paths
- autocomplete-python-jedi
- auto-detect-indentation
- busy-signal
- color-picker
- git-plus
- git-time-machine
- intentions
- keybinding-cheatsheet
- language-ansible
- language-asciidoc
- linter
- linter-ansible-syntax
- linter-ui-default
- linter-pycodestyle
- markdown-pdf
- markdown-preview-plus
- markdown-writer
- merge-conflicts
- minimap-plus
- script
- seti-icons
- vim-mode-plus

# Remove packages that may conflict with installed packages
atom_removed_packages:
- autocomplete-python
- ex-mode
- minimap
- vim-mode

atom_package_dependencies:
- python2-boto3
- python2-botocore
- python2-pycodestyle

#################
# Docker images #
#################
docker_pull_images: yes
docker_images:
- centos:7
- fedora:29
- kalilinux/kali-linux-docker:latest
- registry.access.redhat.com/rhel7:7.6

################
# Go variables #
################
go_packages:
- github.com/derekparker/delve/cmd/dlv

#################
# PIP variables #
#################
pip_packages:
- thefuck
- xkcdpass

pip_package_dependencies:
- python-devel
- redhat-rpm-config

#####################
# libvirt variables #
#####################
libvirt_pool_name: default
libvirt_pool_dir: "{{ ansible_user_dir }}/VirtualMachines"

#####################
# Vagrant variables #
#####################
dnsmasq_listen_interface: wlp4s0

vagrant_plugins:
- landrush
- vagrant-hostmanager
- vagrant-libvirt
- vagrant-registration
- vagrant-scp
- vagrant-service-manager
- vagrant-sshfs

vagrant_plugin_dependencies:
- dnsmasq
- gcc
- gcc-c++
- libvirt
- libvirt-devel
- qemu
- ruby-devel
- rubygem-ruby-libvirt
- zlib-devel

# vagrant_boxes:
