---
# defaults file for fedora_laptop

####################
# Fedora variables #
####################
fedora_installed_packages:
- bash-completion
#- ffmpeg
- gnome-tweak-tool
- ImageMagick
- irssi
- libgnome
- libvirt
- origin-clients
- python-ipython
- python-pudb
- screen
- tmux
- unzip
- virt-manager
- vim
- vim-X11

fedora_third_party_rpms:
- https://github.com/RocketChat/Rocket.Chat.Electron/releases/download/2.4.0/rocketchat-2.4.0.rpm
- https://downloads.slack-edge.com/linux_releases/slack-2.4.2-0.1.fc21.x86_64.rpm

##################
# Atom variables #
##################
atom_packages:
- activate-power-mode
- autocomplete-ansible
- autocomplete-paths
- autocomplete-python
- auto-detect-indentation
- busy-signal
- color-picker
- git-plus
- git-time-machine
- intentions
- keybinding-cheatsheet
- language-ansible
- linter
- linter-ansible-syntax
- linter-ui-default
- linter-pycodestyle
- markdown-pdf
- markdown-preview-plus
- markdown-scroll-sync
- markdown-writer
- merge-conflicts
- minimap
- script
- seti-icons
- vim-mode

atom_package_dependencies:
- python2-pycodestyle

#################
# Docker images #
#################
docker_pull_images: yes
docker_images:
- alpine:3.5
- centos:7
- fedora:25
- kalilinux/kali-linux-docker:Rolling
- mongo:3.4

################
# Go variables #
################
go_packages:
- github.com/derekparker/delve/cmd/dlv

#################
# PIP variables #
#################
pip_packages:
- thefuck

pip_package_dependencies:
- python-devel
- redhat-rpm-config

#####################
# libvirt variables #
#####################
libvirt_pool_name: default
libvirt_pool_dir: "{{ ansible_user_dir }}/VirtualMachines"

#####################
# Vagrant variables #
#####################
dnsmasq_listen_interface: wlp4s0

vagrant_plugins:
- landrush
- ruby-libvirt
- vagrant-hostmanager
- vagrant-libvirt
- vagrant-registration
- vagrant-service-manager
- vagrant-scp
- vagrant-sshfs

vagrant_plugin_dependencies:
- dnsmasq
- gcc
- gcc-c++
- libvirt
- libvirt-devel
- qemu
- ruby-devel
- zlib-devel

# vagrant_boxes:
