---
# defaults file for fedora_laptop

####################
# Fedora variables #
####################
fedora_installed_packages:
# Ansible
- python2-dnf
- libselinux-python
- virt-manager

# Other packages
- bash-completion
- gnome-tweak-tool
- libvirt
- origin-clients
- python-ipython
- python-pudb
- vim
- vim-X11

fedora_third_party_rpms:
- https://github.com/RocketChat/Rocket.Chat.Electron/releases/download/2.4.0/rocketchat-2.4.0.rpm
- https://downloads.slack-edge.com/linux_releases/slack-2.4.2-0.1.fc21.x86_64.rpm

##################
# Atom variables #
##################
atom_packages:
- activate-power-mode
- autocomplete-ansible
#- autocomplete-emojis
- autocomplete-paths
- autocomplete-python
- auto-detect-indentation
- color-picker
- fizzy
- git-plus
- git-time-machine
- keybinding-cheatsheet
- language-ansible
#- language-latex
#- latex
#- latexer
- linter
#- linter-ansible-linting
- linter-ansible-syntax
- linter-pycodestyle
- markdown-pdf
- markdown-preview-plus
- markdown-scroll-sync
- markdown-writer
- merge-conflicts
- minimap
- monokai
- script
- seti-icons
- seti-syntax
- seti-ui
- unity-ui
- vim-mode

atom_package_dependencies:
#- ansible-lint
- python2-pycodestyle

#################
# Docker images #
#################
docker_pull_images: yes
docker_images:
- alpine:3.5
- centos:7
- fedora:25
- kalilinux/kali-linux-docker:Rolling
- mongo:3.4

#################
# PIP variables #
#################
pip_packages:
- thefuck

pip_package_dependencies:
- python-devel
- redhat-rpm-config

#####################
# libvirt variables #
#####################
libvirt_pool_name: default
libvirt_pool_dir: "{{ ansible_user_dir }}/VirtualMachines"

#####################
# Vagrant variables #
#####################
vagrant_plugins:
- landrush
- ruby-libvirt
- vagrant-hostmanager
- vagrant-libvirt
- vagrant-registration
- vagrant-service-manager
- vagrant-sshfs

vagrant_plugin_dependencies:
- dnsmasq
- gcc
- gcc-c++
- libvirt
- libvirt-devel
- qemu
- ruby-devel
- zlib-devel

# vagrant_boxes:
