---
# defaults file for fedora_laptop

####################
# Fedora variables #
####################
fedora_installed_packages:
# Ansible
- python2-dnf
- libselinux-python
- virt-manager
# Other packages
- bash-completion
- python-ipython
- python-pudb
- vim
- vim-X11

##################
# Atom variables #
##################
atom_packages:
- activate-power-mode
- autocomplete-ansible
#- autocomplete-emojis
- autocomplete-paths
- autocomplete-python
- auto-detect-indentation
- color-picker
- fizzy
- git-plus
- git-time-machine
- keybinding-cheatsheet
- language-ansible
#- language-latex
#- latex
#- latexer
- linter
#- linter-ansible-linting
- linter-ansible-syntax
- linter-pycodestyle
- markdown-pdf
- markdown-preview-plus
- markdown-scroll-sync
- markdown-writer
- merge-conflicts
- minimap
- monokai
- script
- seti-icons
- seti-syntax
- seti-ui
- unity-ui
- vim-mode

atom_package_dependencies:
#- ansible-lint
- python2-pycodestyle

#################
# PIP variables #
#################
pip_packages:
- thefuck

pip_package_dependencies:
- python-devel
- redhat-rpm-config

#####################
# Vagrant variables #
#####################
vagrant_plugins:
- landrush
- ruby-libvirt
- vagrant-hostmanager
- vagrant-libvirt
- vagrant-registration
- vagrant-service-manager
- vagrant-sshfs

vagrant_plugin_dependencies:
- dnsmasq
- gcc
- gcc-c++
- libvirt
- libvirt-devel
- qemu
- ruby-devel
- zlib-devel

# vagrant_boxes:
