---
- block:
  - name: install packages
    dnf:
      name: "{{ item }}"
      state: present
    with_items: "{{ fedora_installed_packages }}"

  become: yes
  become_user: root

# Gnome 3 configs
- block:
  # UI settings
  - name: enable minimize and maximize buttons
    command: gsettings set org.gnome.desktop.wm.preferences button-layout "appmenu:minimize,maximize,close"

  - name: make workspaces static
    command: gsettings set org.gnome.shell.overrides dynamic-workspaces false

  - name: set number of workspaces to four
    command: gsettings set org.gnome.desktop.wm.preferences num-workspaces 4

  # Touchpad settings
  - name: modify touchpad settings
    command: gsettings set org.gnome.desktop.peripherals.touchpad {{ item.key }} {{ item.value }}
    with_items:
    # Enable two-finger scrolling
    - key: 'two-finger-scrolling-enabled'
      value: 'true'
    # Enable natural scrolling
    - key: 'natural-scroll'
      value: 'true'
    # Disable tap-to-click on touchpad
    - key: 'tap-to-click'
      value: 'false'
    # Use finger count to determine click type
    # Ex: one finger => left-click
    #     two fingers => right-click
    #     three fingers => middle-click
    - key: 'click-method'
      value: 'fingers'

  - name: create shortcut for lanching terminal
    command: >
      gsettings set
      org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/
      {{ item.key }} "{{ item.value }}"
    with_items:
    - key: 'name'
      value: 'Launch terminal'
    - key: 'command'
      value: '/usr/bin/gnome-terminal'
    - key: 'binding'
      value: '<Primary><Alt><Meta>t'

  - name: create shortcut for lanching browser
    command: >
      gsettings set
      org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom1/
      {{ item.key }} "{{ item.value }}"
    with_items:
    - key: 'name'
      value: 'Launch browser'
    - key: 'command'
      value: '/usr/bin/google-chrome'
    - key: 'binding'
      value: '<Primary><Alt><Meta>b'

  - name: enable custom shortcuts
    command: >
      gsettings set org.gnome.settings-daemon.plugins.media-keys
      custom-keybindings
      "['/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/',
      '/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom1/']"
