---
- name: Install Vagrant
  dnf:
    name: https://releases.hashicorp.com/vagrant/1.8.7/vagrant_1.8.7_x86_64.rpm
    state: present

- name: Install Vagrant plugins
  shell: vagrant plugin install {{ item }}
  with_items:
    - landrush
    - ruby-libvirt
    - vagrant-hostmanager
    - vagrant-libvirt
    - vagrant-registration
    - vagrant-service-manager
    - vagrant-sshfs
  become: yes
  become_user: '{{ default_user }}'

# TODO
#- name: Import boxes
