---
# Install Wireshark
- block:
  - name: install Wireshark
    dnf:
      name: wireshark-qt
      state: present

  - name: add user to wireshark group
    user:
      name: "{{ ansible_user_id }}"
      groups: wireshark
      append: yes
  become: yes
  become_user: root
  tags:
  - wireshark
